# Application name
spring.application.name=orm-learn

# Spring Framework and application logs
logging.level.org.springframework=info
logging.level.com.cognizant=debug

# Hibernate SQL logs
logging.level.org.hibernate.SQL=debug

# Database configuration
spring.datasource.url=jdbc:mysql://localhost:3306/ormlearn
spring.datasource.username=root
spring.datasource.password=admin12345

# Hibernate configuration
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true